FROM ubuntu:xenial
MAINTAINER Pranjal <pranjal@brave.com>

ARG zlib_version
ARG zlib_hash

ARG libevent_version
ARG libevent_hash
ARG libevent_key

ARG openssl_version
ARG openssl_hash

ARG tor_version
ARG tor_hash
ARG tor_key

RUN \
  apt-get update && \
  apt-get install -y build-essential curl autotools-dev automake gnupg2

RUN \ 
  curl -fsSL "https://zlib.net/zlib-${zlib_version}.tar.gz" -o zlib-$zlib_version.tar.gz && \
  echo "$zlib_hash  zlib-$zlib_version.tar.gz" | shasum -a 256 -c - && \
  tar -zxvf zlib-$zlib_version.tar.gz && \
  cd zlib-$zlib_version && \
  ./configure --prefix=$PWD/install && \
  make && make check && make install
  
RUN \  
  curl -fsSL "https://github.com/libevent/libevent/releases/download/release-$libevent_version/libevent-$libevent_version.tar.gz" -o libevent-$libevent_version.tar.gz && \
  curl -fsSL "https://github.com/libevent/libevent/releases/download/release-$libevent_version/libevent-$libevent_version.tar.gz.asc" -o libevent-$libevent_version.tar.gz.asc && \
  gpg --keyserver pool.sks-keyservers.net/ --recv-keys $libevent_key && \
  gpg libevent-$libevent_version.tar.gz.asc && \
  echo "$libevent_hash  libevent-$libevent_version.tar.gz" | shasum -a 256 -c - && \
  tar -zxvf libevent-$libevent_version.tar.gz && \
  cd libevent-$libevent_version && \
  ./configure --prefix=$PWD/install \
              --disable-shared \
              --enable-static \
              --with-pic && \
  make && make check && make install

RUN \
  curl -fsSL "https://www.openssl.org/source/openssl-$openssl_version.tar.gz" -o openssl-$openssl_version.tar.gz && \
  echo "$openssl_hash  openssl-$openssl_version.tar.gz" | shasum -a 256 -c - && \
  tar -xvzf openssl-$openssl_version.tar.gz && \
  cd openssl-$openssl_version && \
  ./config --prefix=$PWD/install no-shared no-dso && \
  make && make test && make install

RUN \  
  curl -fsSL "https://www.torproject.org/dist/tor-$tor_version.tar.gz" -o tor-$tor_version.tar.gz && \
  curl -fsSL "https://www.torproject.org/dist/tor-$tor_version.tar.gz.asc" -o tor-$tor_version.tar.gz.asc && \
  gpg --keyserver pool.sks-keyservers.net/ --recv-keys $tor_key && \
  gpg tor-$tor_version.tar.gz.asc && \
  echo "$tor_hash  tor-$tor_version.tar.gz" | shasum -a 256 -c - && \
  tar -xvzf tor-$tor_version.tar.gz && \
  cd tor-$tor_version && \
  ./configure --prefix=$PWD/install \
              --enable-static-tor \
              --with-libevent-dir=$PWD/../libevent-$libevent_version/install \
              --with-openssl-dir=$PWD/../openssl-$openssl_version/install \
              --with-zlib-dir=$PWD/../zlib-$zlib_version/install \
              --disable-asciidoc && \
  make && make check && make install

ENTRYPOINT while :; do read; done
