FROM ubuntu:focal
MAINTAINER Pranjal <pranjal@brave.com>

ARG zlib_version
ARG zlib_hash

ARG libevent_version
ARG libevent_hash

ARG openssl_version
ARG openssl_hash

ARG tor_version
ARG tor_hash

ARG jobs

COPY gpg-keys/tor.gpg /tor.gpg
COPY gpg-keys/libevent.gpg /libevent.gpg

RUN \
  apt-get update && \
  apt-get install -y build-essential curl autotools-dev automake gnupg2

RUN \ 
  curl -fsSL "https://zlib.net/zlib-${zlib_version}.tar.gz" -o zlib-$zlib_version.tar.gz && \
  shasum -a 256 zlib-$zlib_version.tar.gz && \
  echo "$zlib_hash  zlib-$zlib_version.tar.gz" | shasum -a 256 -c - && \
  tar -zxvf zlib-$zlib_version.tar.gz && \
  cd zlib-$zlib_version && \
  ./configure --prefix=$PWD/root && \
  make ${jobs:+-j${jobs}} && make ${jobs:+-j$jobs} check && make install

RUN \
  curl -fsSL "https://www.openssl.org/source/openssl-$openssl_version.tar.gz" -o openssl-$openssl_version.tar.gz && \
  shasum -a 256 openssl-$openssl_version.tar.gz && \
  echo "$openssl_hash  openssl-$openssl_version.tar.gz" | shasum -a 256 -c - && \
  tar -xvzf openssl-$openssl_version.tar.gz && \
  cd openssl-$openssl_version && \
  ./config --prefix=$PWD/root no-shared no-dso && \
  make ${jobs:+-j$jobs} && make test && make install

RUN \  
  curl -fsSL "https://github.com/libevent/libevent/releases/download/release-$libevent_version/libevent-$libevent_version.tar.gz" -o libevent-$libevent_version.tar.gz && \
  curl -fsSL "https://github.com/libevent/libevent/releases/download/release-$libevent_version/libevent-$libevent_version.tar.gz.asc" -o libevent-$libevent_version.tar.gz.asc && \
  gpg --keyring /libevent.gpg --verify libevent-$libevent_version.tar.gz.asc libevent-$libevent_version.tar.gz && \
  shasum -a 256 libevent-$libevent_version.tar.gz && \
  echo "$libevent_hash  libevent-$libevent_version.tar.gz" | shasum -a 256 -c - && \
  tar -zxvf libevent-$libevent_version.tar.gz && \
  cd libevent-$libevent_version && \
  ./configure \
              LDFLAGS="-L$PWD/../openssl-$openssl_version/root" \
              CPPFLAGS="-I$PWD/../oppenssl-$openssl_version/include" \
              --prefix=$PWD/install \
              --disable-shared \
              --enable-static \
              --with-pic && \
  ulimit -n 65536 && \
  make ${jobs:+-j$jobs} && make ${jobs:+-j$jobs} check && make install

RUN \  
  curl -fsSL "https://www.torproject.org/dist/tor-$tor_version.tar.gz" -o tor-$tor_version.tar.gz && \
  curl -fsSL "https://www.torproject.org/dist/tor-$tor_version.tar.gz.asc" -o tor-$tor_version.tar.gz.asc && \
  gpg --keyring /tor.gpg --verify tor-$tor_version.tar.gz.asc tor-$tor_version.tar.gz && \
  shasum -a 256 tor-$tor_version.tar.gz && \
  echo "$tor_hash  tor-$tor_version.tar.gz" | shasum -a 256 -c - && \
  tar -xvzf tor-$tor_version.tar.gz && \
  cd tor-$tor_version && \
  ./configure --prefix=$PWD/install \
              --enable-static-tor \
              --with-libevent-dir=$PWD/../libevent-$libevent_version/install \
              --with-openssl-dir=$PWD/../openssl-$openssl_version/root \
              --with-zlib-dir=$PWD/../zlib-$zlib_version/root \
              --disable-asciidoc && \
  make ${jobs:+-j$jobs} && make ${jobs:+-j$jobs} check && make install

ENTRYPOINT ["sh", "-c", "while true; do sleep 2; done"]
